### ISSUE TITLE
KDE colorscheme symlinks

### ISSUE THREAD

**Issue by Dejweed** [kuroehanako/Stylish-icon-theme#3]
I manually copied all files from alternatives/kde-colorscheme to places but they aren't applied for Downloads, Public, Templates, Videos... because they use icon names like folder-downloads instead of folder-download and are symlinked to folder-blue-download. Maybe you could link folder-downloads to folder-download, unless there is a script for installing colorscheme icons.
I know this is a work in progress but just wanted to let you know.

![Screenshot_2022-11-28_13-29-21](https://user-images.githubusercontent.com/65261588/204350520-360bec40-3253-4a36-b30f-1e7981cb803d.png)
Keep up the good work :)

**Comment by nestoris** [comment]
Please, do a pull request to my theme, so I'll can merge your changes.

**Comment by kuroehanako** [comment]
KDE ColorScheme Version isn't completed.

**Comment by kuroehanako** [comment]
v23.05 is released now with KDE ColorScheme Variant!
